Repository dsnehasish74/Hacktoberfest21_Algo_Collection, pull requests merged in 2021-10, with the labels that each got.

#4 DFS and BFS added
  treebfs.cpp
  treedfs.cpp
Labels: hacktoberfest-accepted

#3 Create quicksort.c
  quicksort.c
Labels: hacktoberfest-accepted

#5 Mergesort added
  mergesort.c
Labels: hacktoberfest-accepted

#7 Quicksort Sort
  Quicksort Sort.py
Labels: hacktoberfest-accepted

#10 Added merge sort in c++
  merge_sort.cpp
Labels: hacktoberfest-accepted

#9 Algorithm of polygon triangulation added in cpp
  polygon_triangulation.cpp
Labels: hacktoberfest-accepted

#8 Added quicksort in CPP
  quick_sort.cpp
Labels: hacktoberfest-accepted

#12 Binary Search Algorithm in C++
  BinarySearch.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#13 Create Selection Sort
  Selection Sort
Labels: hacktoberfest-accepted

#15 DNFsort solution added
  DNFsort.cpp
Labels: hacktoberfest

#14 Bubble Sort
  Bubblesort.py
Labels: hacktoberfest-accepted

#17 Added Kanade's Algorithm
  kanade-algorithm.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#18 Dijkstra Algorithm CPP
  DijkstraAlgo.cpp
Labels: hacktoberfest-accepted

#21 Insertion Sort Added
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/settings.json
  insertionSort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#20 Radix Sort Algo
  RadixSort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#19 Issue #6 - Added Insertion Sort
  insertion_sort.py
Labels: hacktoberfest, hacktoberfest-accepted

#23 Added Merge Sort Algo in Java
  MergeSort.java
Labels: hacktoberfest, hacktoberfest-accepted

#24 Tower of Hanoi in cpp
  tower-of-hanoi.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#26 Create Heap_sort.cpp
  Heap_sort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#35 Circular Linked List Insertion and deletion
  C++/Circular_Linked_List_Insertion_deletion.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#32 Sliding_Window added
  C++/Sliding_window_tech.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#40 Sorting Programs are added in java Bubble,Selection,Insertion,Cyclic Sort
  Java/BubbleSort.java
  Java/CyclicSort.java
  Java/InsertionSort.java
  Java/SelectionSort.java
Labels: hacktoberfest, hacktoberfest-accepted

#33 create-string-match.cpp
  C++/string-match.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#42 Create countSort.c
  C/countSort.c
Labels: hacktoberfest, hacktoberfest-accepted

#41 Create merge_sort.py
  Python/merge_sort.py
Labels: hacktoberfest, hacktoberfest-accepted

#28 Create Infix_to_pre_post_fix.cpp
  C++/Infix_to_prefix_postfix.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#43 created bubble sort
  C++/bubble_sort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#34 Segment Tree added
  Python/SegemntTree.py
  Python/avlTree.py
Labels: hacktoberfest, hacktoberfest-accepted

#44 Added first unique character solution
  Python/first_unique_character.py
Labels: hacktoberfest, hacktoberfest-accepted

#45 Stack
  C++/Insertion_and_deletion_in_Stack.cpp
  C++/LinkedListDeletion.cpp
  C++/Linked_list_Insertion.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#49 Traverse a singly linked list
  C/Traverse Singly Linked List.c
Labels: hacktoberfest, hacktoberfest-accepted

#55 Tower of Hanoi in C
  C++/LinkedListDeletion.cpp
  C++/Linked_list_Insertion.cpp
  C/TowerOfHanoi.c
Labels: hacktoberfest, hacktoberfest-accepted

#54 snake_game.cpp
  C++/snake_game.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#56 Counting Sort added
  C++/Counting_sort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#52 Selection sort in python
  Python/Selection_sort.py
Labels: hacktoberfest, hacktoberfest-accepted

#46 adding dijkstra's algo
  Python/dijkstra.py
Labels: hacktoberfest, hacktoberfest-accepted

#51 Create Floyd's Triangle
  Python/Floyd's Triangle
Labels: hacktoberfest, hacktoberfest-accepted

#50 Quick Sort Algorithm in Java
  Java/Quick_sort.java
Labels: hacktoberfest, hacktoberfest-accepted

#48 Added HeapSort in Java
  Java/HeapSort.java
Labels: hacktoberfest, hacktoberfest-accepted

#57 Create Z Algorithm.java
  Java/Z Algorithm.java
Labels: hacktoberfest, hacktoberfest-accepted

#59 Create 8-queens.py
  Python/8-queens.py
Labels: hacktoberfest, hacktoberfest-accepted

#58 Created program for coin change problem
  C++/Greedyalgo_coinchange.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#66 Updated README & Added contribution guidelines
  C++/binary-search.cpp
  C++/bubble-sort.cpp
  C++/circular-linked-list-insertion-deletion.cpp
  C++/counting-sort.cpp
  C++/dijkstras-algorithm.cpp
  C++/dnf-sort.cpp
  C++/greedyalgo-coinchange.cpp
  C++/heap-sort.cpp
  C++/infix-to-prefix-postfix.cpp
  C++/insertion-and-deletion-in-stack.cpp
  C++/insertion-sort.cpp
  C++/linked-list-deletion.cpp
  C++/linked-list-insertion.cpp
  C++/merge-sort.cpp
  C++/polygon-triangulation.cpp
  C++/quick-sort.cpp
  C++/radix-sort.cpp
  C++/selection-sort.cpp
  C++/sliding-window-tech.cpp
  C++/snake-game.cpp
  C++/tree-bfs.cpp
  C++/tree-dfs.cpp
  C/count-sort.c
  C/merge-sort.c
  C/quick-sort.c
  C/tower-of-hanoi.c
  C/traverse-singly-linked-list.c
  CONTRIBUTING.md
  Java/bubble-sort.java
  Java/cyclic-sort.java
  Java/heap-sort.java
  Java/insertion-sort.java
  Java/merge-sort.java
  Java/quick-sort.java
  Java/selection-sort.java
  Java/z-algorithm.java
  Python/avl-tree.py
  Python/bubble-sort.py
  Python/dijkstras-algorithm.py
  Python/first-unique-character.py
  Python/floyds-triangle.py
  Python/insertion-sort.py
  Python/merge-sort.py
  Python/quicksort-sort.py
  Python/segment-tree.py
  Python/selection-sort.py
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#67 Added knapsack
  Python/knapsack.py
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#63 N_Queens Backtracking Problem
  C++/n-queens-backtracking.cpp
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#68 adding folder and html file
  HTML/site-music.html
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#82 Added Generic Tree Implementation in C
  C/generic-tree.c
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#85 Add Algorithm
  C/floyds-all-pair-shortest-path.c
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#69 Binary Search Added
  Python/binary-search.py
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#91 Added Edmonds-Karp Algorithm
  C++/edmonds-karp-algorithm.cpp
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#92 Bubble Sort in Swift
  README.md
  Swift/bubble-sort.swift
Labels: hacktoberfest, hacktoberfest-accepted
